mysql_configs:
  - name: test_sql
    sqlDir: ./sql
    database: test_sql
    connectInfo:
      host: 192.168.1.1
      user: root
      port: 3306
      password: "123456"
      charset: utf8
    is_use: false
